[package]
name = "superellipse"
version = "0.1.0"
edition = "2021"

[features]
skia = ["dep:skia-safe"]

[dependencies]
skia-safe = { version = "0.80.1", optional = true }

[dev-dependencies]
softbuffer = "0.4.6"
winit = "0.30.7"

[[example]]
name = "skia-window"
required-features = ["skia"]
